// GENERATED by `npm run photos` — do not edit by hand, your changes will be lost.
// Source: project-images/<slug>/… · output: public/images/project/<slug>/<id>-<width>.avif
// FRAMEWORK-FREE (see types.ts · landmine C1) — vite.config.ts may read this in Node.

import type { ProjectImages } from './types';

/** Keyed by project slug = the folder name under project-images/. Shots in filename order. */
export const projectImages: Record<string, ProjectImages> = {
  'k-ranking-list': {
    cover: { id: 'cover', width: 700, height: 468, widths: [700] },
    shots: [],
  },
  'portfolio': {
    cover: { id: 'cover', width: 1400, height: 827, widths: [700, 1400] },
    shots: [],
  },
  'recipevault': {
    cover: { id: 'cover', width: 1400, height: 819, widths: [700, 1400] },
    shots: [],
  },
  'rising-sigmas': {
    cover: { id: 'cover', width: 1400, height: 827, widths: [700, 1400] },
    shots: [],
  },
};
